CREATE DATABASE IF NOT EXISTS todoapp;
CREATE USER 'todo' @'%' IDENTIFIED BY '123';
GRANT SELECT,
    INSERT,
    UPDATE,
    DELETE ON todoapp.* TO 'todo' @'%';
USE todoapp;
CREATE TABLE IF NOT EXISTS todos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200),
    completed BOOLEAN
);